---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC170.
--- DateTime: 2024/5/11 11:23
---
local common=require("core.common")
local common1=common:new("lind")


local status, result = pcall(common1.divide, 10, 2)
if status then
    print("结果：", result)
else
    print("发生错误：", result)
end
