---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC170.
--- DateTime: 2024/5/11 11:23
---
local common = require("core.common")
local common1 = common:new("lind")

local status, result = pcall(common1.divide, 10, 2)
if status then
    print("结果：", result)
else
    print("发生错误：", result)
end

local function isPathMatched(request_uri, config_paths)
    for _, path in ipairs(config_paths) do
        local pattern = "^" .. string.gsub(path, "*", "[^/]*") .. "/?$" -- 匹配路径前缀
        --local pattern = string.gsub(path, "*", ".*") --模糊配置
        if string.match(request_uri, pattern) then
            return true
        end
    end
    return false
end
print("--1--")

local config_paths = { "/test*" }
print(isPathMatched("/test-free", config_paths)) --true
print(isPathMatched("/test", config_paths)) --true
print(isPathMatched("/test/123", config_paths)) --false
print(isPathMatched("/test?name=zzl", config_paths)) --true
print(isPathMatched("/user-register/test?name=zzl", config_paths)) --true

print("--2--")
local config_paths2 = { "/test/*" }
print(isPathMatched("/user-register/test/123", config_paths2)) --true
print(isPathMatched("/test/name=zzl", config_paths2)) --true
print(isPathMatched("/test/123/456", config_paths2)) --false
print(isPathMatched("/test/123", config_paths2)) --true

local function isPathMatched(request_uri, config_paths)
    for _, path in ipairs(config_paths) do
        local pattern = "^" .. string.gsub(path, "*", "[^/]*") .. ".*$"
        if string.match(request_uri, pattern) then
            return true
        end
    end
    return false

end
print("--3--")
print(isPathMatched("/test", config_paths))
print(isPathMatched("/test?a=1", config_paths))
print(isPathMatched("/test/1", config_paths))
print(isPathMatched("/test/1?a=1", config_paths))
print(isPathMatched("/test-1", config_paths))
print(isPathMatched("/a/testa1", config_paths))

-- string.gsub字符替换
local original_uri="/user-register/user/test"
local new_uri = string.gsub(original_uri, "^/user%-register", "/fabao-api") --表示匹配以 /user-register 开头的字符串，其中 % 是转义字符，因为 - 在 Lua 模式中有特殊含义。
print("new_uri："..new_uri)
